{{- if and .Values.saleor.persistence.enabled (not .Values.saleor.persistence.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "saleor.fullname" . }}
  labels:
    app: {{ template "saleor.name" . }}
    chart: {{ template "saleor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.saleor.persistence.storageClass }}
  storageClassName: {{ .Values.saleor.persistence.storageClass }}
{{- end }}
  accessModes:
    - {{ .Values.saleor.persistence.accessMode }}
  resources:
      requests:
        storage: {{ .Values.saleor.persistence.size | quote }}
  volumeMode: {{ .Values.saleor.persistence.volumeMode }}
  persistentVolumeReclaimPolicy: {{ .Values.saleor.persistence.persistentVolumeReclaimPolicy }}
{{- end -}}
