dependencies:
  - name: postgresql
    version: "3.0.0"
    repository: "https://kubernetes-charts.storage.googleapis.com"
  - name: redis
    version: "4.2.1"
    repository: "https://kubernetes-charts.storage.googleapis.com"
